const Character = require('./Character.js')
const Thief = require('./Thief.js')
const Mage = require('./Mage.js')
const Warrior = require('./Warrior.js')

const thief = new Thief("thief", 150, 20, 10)
const mage = new Mage("mage", 100, 5, 10, 30)
const warrior = new Warrior("warrior", 200, 20, 15, 15)

console.table({ thief, mage, warrior })

thief.attack(warrior)
mage.healAlly(warrior)
thief.attack(mage)
thief.attack(mage)
thief.attack(mage)
mage.healAlly(mage)
warrior.changePosition()
thief.attack(warrior)
warrior.attack(thief)
warrior.changePosition()
warrior.attack(thief)
mage.attack(thief)
mage.attack(thief)
mage.attack(thief)
mage.attack(thief)
mage.attack(thief)
mage.attack(thief)

console.table({ thief, mage, warrior })